import type { Config } from "tailwindcss";

import typography from "@tailwindcss/typography"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Chromatic Accent Tokens (blue-spectrum) ──
        "chromatic-sunset": "hsl(var(--chromatic-sunset))",
        "chromatic-sunset-end": "hsl(var(--chromatic-sunset-end))",
        "chromatic-ocean": "hsl(var(--chromatic-ocean))",
        "chromatic-ocean-end": "hsl(var(--chromatic-ocean-end))",
        "chromatic-aurora": "hsl(var(--chromatic-aurora))",
        "chromatic-gold": "hsl(var(--chromatic-gold))",
        "chromatic-coral": "hsl(var(--chromatic-coral))",
        "chromatic-amber": "hsl(var(--chromatic-amber))",
        // ── Missing chromatic tokens ──
        "chromatic-sky": "hsl(var(--chromatic-sky))",
        "chromatic-mint": "hsl(var(--chromatic-mint))",
        "chromatic-ice": "hsl(var(--chromatic-ice))",
        // ── Semantic tokens (CSS-var backed) ──
        "primary-fixed": "hsl(var(--primary-fixed))",
        "on-primary-fixed": "hsl(var(--on-primary-fixed))",
        "on-primary-fixed-variant": "hsl(var(--on-primary-fixed-variant))",
        "stay-purple": "hsl(var(--stay-purple))",
        "on-secondary-fixed": "hsl(var(--on-secondary-container))",
        "on-secondary-fixed-variant": "hsl(var(--on-secondary-fixed-variant))",
        "budget-green": "hsl(var(--budget-green))",
        "transport-blue": "hsl(var(--transport-blue))",
        "note-yellow": "hsl(var(--note-yellow))",
        "destructive-red": "hsl(var(--destructive-red))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        "on-primary": "hsl(var(--on-primary))",
        "on-secondary-container": "hsl(var(--on-secondary-container))",
        "on-background": "hsl(var(--on-background))",
        "on-surface-variant": "hsl(var(--on-surface-variant))",
        "on-tertiary-fixed-variant": "hsl(var(--on-tertiary-fixed-variant))",
        "surface-dim": "hsl(var(--surface-dim))",
        "surface-container-highest": "hsl(var(--surface-container-highest))",
        outline: "hsl(var(--outline))",
        error: "hsl(var(--error))",
        "surface-tint": "hsl(var(--surface-tint))",
        "tertiary-fixed-dim": "hsl(var(--tertiary-fixed-dim))",
        "error-container": "hsl(var(--error-container))",
        "surface-container-low": "hsl(var(--surface-container-low))",
        "secondary-fixed": "hsl(var(--secondary-fixed))",
        "inverse-on-surface": "hsl(var(--inverse-on-surface))",
        "secondary-container": "hsl(var(--secondary-container))",
        "inverse-primary": "hsl(var(--inverse-primary))",
        "inverse-surface": "hsl(var(--inverse-surface))",
        "surface-container": "hsl(var(--surface-container))",
        "on-secondary": "hsl(var(--on-secondary))",
        "surface-container-high": "hsl(var(--surface-container-high))",
        "secondary-fixed-dim": "hsl(var(--secondary-fixed-dim))",
        "on-error": "hsl(var(--on-error))",
        "on-error-container": "hsl(var(--on-error-container))",
        "on-surface": "hsl(var(--on-surface))",
        "surface-container-lowest": "hsl(var(--surface-container-lowest))",
        "on-tertiary-container": "hsl(var(--on-tertiary-container))",
        "primary-fixed-dim": "hsl(var(--primary-fixed-dim))",
        "on-primary-container": "hsl(var(--on-primary-container))",
        "outline-variant": "hsl(var(--outline-variant))",
        "surface-bright": "hsl(var(--surface-bright))",
        "on-tertiary-fixed": "hsl(var(--on-tertiary-fixed))",
        "on-tertiary": "hsl(var(--on-tertiary))",
        "surface-variant": "hsl(var(--surface-variant))",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "max-width": "1200px",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
        "unit": "4px",
        "gutter": "1.5rem",
        "6": "1.5rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        heading: ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-sm": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-geist-sans)", "Geist", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist-sans)", "Geist", "sans-serif"],
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        "shimmer-sparkle": {
          "0%, 100%": { opacity: "0" },
          "50%": { opacity: "0.6" },
        },
        "gradient-shift": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        "float-orb": {
          "0%, 100%": { transform: "translate(0, 0) scale(1)" },
          "33%": { transform: "translate(30px, -30px) scale(1.05)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.95)" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(59, 130, 246, 0.15)" },
          "50%": { boxShadow: "0 0 40px rgba(59, 130, 246, 0.3)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.8s ease-in-out infinite",
        "shimmer-sparkle": "shimmer-sparkle 2s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease-in-out infinite",
        "float-orb": "float-orb 12s ease-in-out infinite",
        "fade-up": "fade-up 0.4s ease-out both",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.025em", fontWeight: "700" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  safelist: [
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "md:grid-cols-2",
    "lg:grid-cols-3",
    "md:grid-cols-4",
    "gap-6",
  ],
  plugins: [typography],
};
export default config;
